media:
  input: images
  output: /images
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: title
        type: string
        label: Title
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
  - name: news
    label: News
    path: news
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
  - name: products
    label: Products
    path: products
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: title
        type: string
        label: Title
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: gallery
        type: image
        label: Gallery
        options:
          input: images
          output: /images
          multiple: true
          extensions: [jpg]
  - name: categories
    label: Categories
    path: categories
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: title
        type: string
        label: Title
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
