media:
  input: images
  output: /images
content:
  - name: pages
    label: Pages
    path: pages
    type: collection
    subfolders: false
    view:
      fields: [ id, name, meta_title, header_text ]
      primary: name
      sort: [ order, name ]
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: eleventyNavigation
        label: Navigation
        type: object
        fields:
        - name: key
          type: string
        - name: order
          type: number
        - name: url
          type: string
      - name: layout
        type: string
        hidden: true
      - name: permalink
        type: string
        hidden: true
  - name: news
    label: News
    path: news
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
  - name: products
    label: Products
    path: products
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: title
        type: string
        label: Title
      - name: categories
        label: Categories
        type: reference
        options:
          collection: categories
          multiple: true
          search: "title"
          value: "{name}"
          label: "{title}"
      - name: price
        label: Price
        type: number
        options:
          min: 1
      - name: body
        label: Body
        type: code
        options:
          language: markdown
      - name: features
        type: select
        options:
          creatable: true
          multiple: true
      - name: gallery
        type: image
        label: Gallery
        options:
          input: images
          output: /images
          multiple: true
          extensions: [jpg]
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
  - name: categories
    label: Categories
    path: categories
    type: collection
    fields:
      - name: header_image
        type: image
        label: Header Image
        options:
          input: images
          output: /images
          extensions: [jpg]
      - name: title
        type: string
        label: Title
      - name: header_text
        type: string
        label: Header Text
      - name: meta_description
        type: string
        label: Meta Description
      - name: meta_title
        type: string
        label: Meta Title
      - name: subtitle
        type: string
        label: Subtitle
      - name: body
        label: Body
        type: code
        options:
          language: markdown
