name: Build and Deploy to Neocities

on:
  push:
  workflow_dispatch:

env:
  NIX_PATH: nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos
  NEOCITIES_API_KEY: ${{ secrets.NEOCITIES_API_KEY }}

jobs:
  build:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update site.json with secrets
        run: |
          sed -i 's/"formspark_id": "[^"]*"/"formspark_id": "${{ secrets.FORMSPARK_ID }}"/g' _data/site.json
          sed -i 's/"botpoison_public_key": "[^"]*"/"botpoison_public_key": "${{ secrets.BOTPOISON_PUBLIC_KEY }}"/g' _data/site.json

      - name: Build
        id: build
        run: |
          DEPLOY_PATH="$GITHUB_WORKSPACE/dist"
          mkdir -p "$DEPLOY_PATH"
          nix-fast-build --skip-cached --flake ".#packages.x86_64-linux.site" --no-nom
          cp -r result-/* "$DEPLOY_PATH"/

      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.0.6
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: "./dist"
          storage-endpoint: "https://uk.storage.bunnycdn.com"
          storage-zone-name: "southport-organics"
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          concurrency: "5"
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: "3576287"
          replication-timeout: "15000"
