name: Build and Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout Chobble Template
        uses: actions/checkout@v4
        with:
          repository: chobble-mirror/chobble-template
          ref: main
          path: template
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .eleventy.js
            package.json
            package-lock.json
            flake.nix
            flake.lock
            bin
            src

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            combined/node_modules
            combined/.image-cache
          key: ${{ runner.os }}-node-${{ hashFiles('combined/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Copy template files to combined dir
        run: |
          mkdir combined
          rsync \
            --recursive \
            --verbose \
            --delete \
            --exclude=".git" \
            --exclude="*.md" \
            --exclude="images" \
            template/ \
            combined/

      - name: Overlay our repo files into combined src
        run: |
          rsync \
            --recursive \
            --verbose \
            --exclude=".git" \
            --exclude="bin/build" \
            --exclude="README.md" \
            source/ \
            combined/src/

      - name: Update site.json with secrets
        run: |
          sed -i \
            's/"formspark_id": null/"formspark_id": "${{ secrets.FORMSPARK_ID }}"/g' \
            "combined/src/_data/site.json"
          sed -i \
            's/"botpoison_public_key": null/"botpoison_public_key": "${{ secrets.BOTPOISON_PUBLIC_KEY }}"/g' \
            "combined/src/_data/site.json"

      - name: Build with Node
        run: |
          cd combined
          npm install
          npx @11ty/eleventy
          mv _site ../

      - name: Deploy to Bunny
        uses: R-J-dev/bunny-deploy@v2.0.6
        with:
          access-key: ${{ secrets.BUNNY_ACCESS_KEY }}
          directory-to-upload: "_site"
          storage-endpoint: "https://uk.storage.bunnycdn.com"
          storage-zone-name: "southport-organics"
          storage-zone-password: ${{ secrets.BUNNY_STORAGE_ZONE_PASSWORD }}
          concurrency: "5"
          enable-delete-action: true
          enable-purge-pull-zone: true
          pull-zone-id: "3576287"
          replication-timeout: "15000"
